//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NGUYENLIEU()
        {
            this.CT_PHIEUNHAPKHO = new HashSet<CT_PHIEUNHAPKHO>();
            this.CT_SANPHAM_NGUYENLIEU = new HashSet<CT_SANPHAM_NGUYENLIEU>();
        }
    
        public string MANL { get; set; }
        public string MALNL { get; set; }
        public string TENNL { get; set; }
        public string DVT { get; set; }
        public Nullable<System.DateTime> HSD { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAPKHO> CT_PHIEUNHAPKHO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_SANPHAM_NGUYENLIEU> CT_SANPHAM_NGUYENLIEU { get; set; }
        public virtual LOAINL LOAINL { get; set; }
    }
}
